In [15]:
import pandas as pd

In [16]:
df = pd.read_csv("./data/recordings_data.csv")

df.head(5)

,Unnamed: 0,audio_id,chunk_id,transcript
0,0,92005f1a713e47cb83667a4300eedc84,1,"Sir, how is the signature? Is it a hidden cop..."
1,1,181019ba1580492687bfab6a9d8d6451,3,"I have sent it in the morning. Yes, this amou..."
2,2,181019ba1580492687bfab6a9d8d6451,2,"Hello ma'am, I am Koshal speaking. Yes, pleas..."
3,3,181019ba1580492687bfab6a9d8d6451,1,"Good morning, Chester. I am Aishwarya. How ar..."
4,4,2226fca493a54603a9ec15decd26f1b1,3,Okay. Thank you so much for your time.

In [19]:
df = df.drop(columns=["Unnamed: 0"])

In [21]:
from IPython.display import Displa

,audio_id,chunk_id,transcript
0,92005f1a713e47cb83667a4300eedc84,1,"Sir, how is the signature? Is it a hidden cop..."
1,181019ba1580492687bfab6a9d8d6451,3,"I have sent it in the morning. Yes, this amou..."
2,181019ba1580492687bfab6a9d8d6451,2,"Hello ma'am, I am Koshal speaking. Yes, pleas..."
3,181019ba1580492687bfab6a9d8d6451,1,"Good morning, Chester. I am Aishwarya. How ar..."
4,2226fca493a54603a9ec15decd26f1b1,3,Okay. Thank you so much for your time.
...,...,...,...
1357,3892281a35f5427caad95dac2ae6e198,5,Hello.
1358,3892281a35f5427caad95dac2ae6e198,4,"So you have to fill in the segment, which seg..."
1359,3892281a35f5427caad95dac2ae6e198,3,"If you go to the Choice Phoenix App, then go ..."
1360,3892281a35f5427caad95dac2ae6e198,2,"No sir, you have to activate the segment for ..."
1361,3892281a35f5427caad95dac2ae6e198,1,"Good morning sir, this is Choice Phoenix, how..."